# Generated by Django 5.2.4 on 2025-11-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_event_photo_alter_event_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, default='event_img/20943471.jpg', null=True, upload_to='event_img'),
        ),
    ]
