# Generated by Django 5.2.4 on 2025-07-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='p_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
